### ISSUE TITLE
Add follow feature to Chirp

### ISSUE THREAD

**Issue by victormemborg** [ITU-BDSA2024-GROUP23/Chirp#81]
We need to add a follow/unfollow feature to chirp. Users should be able to follow any other user except themselves.

Acceptance criteria:
**Public timeline:**
- [x] Links labeled "follow" appear next to all usernames for users the authenticated user is not following.
- [x] Links labeled "unfollow" appear next to usernames of users the authenticated user is following.
- [x] Clicking these links updates the follow status and redirects to current page

**Private timeline:**

- [x] An authenticated user sees cheeps from themselves and the users they follow.
- [x] Links labeled "follow" appear next to all usernames for users the authenticated user is not following.
- [x] Links labeled "unfollow" appear next to usernames of users the authenticated user is following.
- [x] When visiting another user's private timeline the authenticated user sees only the cheeps written by that specific user, regardless of who the visited user is following.

**Comment by victormemborg** [comment]
Jeg har implementeret meget, men der skal ryddes op. Der er tilføjet

- Follower model
- Update i DBContext
- Follow/unfollow commands i repo
- Du kan pt følge en, og når du går ind på din egen timeline, bliver dine fulgte brugere også vist
- Knap til at følge brugere på private timeline

**TODO:**
- Refactor evt. messagelist ud i sit eget partial view
- Find en metode at finde ud af om en bruger allerede følger brugeren i cshtml (både public og private)
- Cleanup code som er skrevet af GitHub copilot - repo, usertimeline.cshtml og usertimeline.cshtml.cs

**Comment by victormemborg** [comment]
Jeg har rykket messagelist ud i sin egen partial - "_CheepList"
